services:
  mysql:
    image: mysql:8.0
    container_name: shopify-subscription-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopify_subscription_app
    ports:
      - "3306:3306"
    volumes:
      - shopify_mysql_data:/var/lib/mysql

volumes:
  shopify_mysql_data:
