# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "256f386983be7a5df0973719cc96ebd5"
name = "sub-app-new"
application_url = "https://stopwatch-research-dove.ngrok-free.dev/"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_contracts/create"
  topics = [ "subscription_contracts/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/subscription_contracts/update"
  topics = [ "subscription_contracts/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_purchase_options,read_purchase_options,read_own_subscription_contracts,write_own_subscription_contracts,write_customers,read_customers,write_orders,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
